<a href="https://colab.research.google.com/github/MankotiaGit/First_Sem_Project/blob/main/Btech_CSE_2024_others.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#immutability
my_sub = "Hello"
my_sub[0] = "C"

TypeError: 'str' object does not support item assignment

In [ ]:
#concatenation --addition of string
first_name = "Jai"
last_name = "Singh"
my_name = first_name +" "+ last_name
print(my_name)

Jai Singh


In [ ]:
my_city = "Solan"
len(my_city)

5

In [ ]:
my_city.lower()

'solan'

In [ ]:
my_city.upper()

'SOLAN'

In [ ]:
algorthim = "Neural Networke"
algorthim.count("e", 2, 14)

1

In [ ]:
#find--this method used to find the index of item
algorthim.find("e", 2, 14)

8

In [ ]:
algorthim.replace("N", "M")

'Meural Metworke'

In [ ]:
my_list = [23, 78, 90, 67, 45]
print(my_list)
my_list.append(100) #this method used to add item end of the list
print(my_list)


[23, 78, 90, 67, 45]
[23, 78, 90, 67, 45, 100]


In [ ]:
my_list

[23, 78, 90, 67, 45, 100]

In [ ]:
list1 = [45, 87, 90]
my_list.extend(list1) #merge the two list
print(my_list)

[23, 78, 90, 67, 45, 100, 45, 87, 90]


In [ ]:
#pop() --remove the item from the list with help of index
my_list

[23, 78, 90, 67, 45, 100, 45, 87, 90]

In [ ]:
my_list.pop()

90

In [ ]:
my_list.pop(1)

78

In [ ]:
print(my_list)

[23, 90, 67, 45, 100, 45, 87]


In [ ]:
my_list.remove(45) #this method remove the item from the list, item take as a argument

In [ ]:
print(my_list)

[23, 90, 67, 100, 45, 87]


In [ ]:
my_list.remove(23)

In [ ]:
my_list

[90, 67, 100, 45, 87]

In [ ]:
my_list.index(90)

0

In [ ]:
my_list = [1, 4, 8, 9, 4, 5, 6, 3]
sorted(my_list, reverse = True) #arrange your list in increasing or decreasing order

[9, 8, 6, 5, 4, 4, 3, 1]

In [ ]:
print(my_list)

[1, 4, 8, 9, 4, 5, 6, 3]


In [ ]:
my_list.sort(reverse = True)
print(my_list)

[9, 8, 6, 5, 4, 4, 3, 1]


In [ ]:
my_tuple = (2, 4, 8, 9)
type(my_tuple)

tuple

In [ ]:
x = 1, 2, 3
type(x)

tuple

In [ ]:
y = ()
type(y)

tuple

In [ ]:
z = (2)
type(z)

int

In [ ]:
a = (2,)
type(a)

tuple

In [ ]:
my_tuple = ("jagat", 3.24, 8, True, None)
type(my_tuple)

tuple

In [ ]:
len(my_tuple)

5

In [ ]:
#immutable --- data structure not change after construct
my_tuple[0] = 100
my_tuple

TypeError: 'tuple' object does not support item assignment

In [ ]:
state_list = ["HP", "UP", "HAR", "PUN", "TN"]
city_list = ["SHM", "LK", "GRU", "MOH", "CHN"]
x = zip(state_list, city_list)
x

In [ ]:
dict(x)

{'HP': 'SHM', 'UP': 'LK', 'HAR': 'GRU', 'PUN': 'MOH', 'TN': 'CHN'}

In [ ]:
my_tuple = (6, 5, 7, 6, 8)
my_tuple.count(6) # count the number of perticular item

2

In [ ]:
my_tuple.index(6) #find the index of first accurance


0

In [ ]:
#set -- collection of unique number of item
x = " "
type(x)

str

In [ ]:
y = []
type(y)

list

In [ ]:
z = ()
type(z)

tuple

In [ ]:
my_set = {3, 6, 7, 8}
type(my_set)

set

In [ ]:
a = {}
type(a)

dict

In [ ]:
empty_set = set()
type(empty_set)

set

In [ ]:
my_set = {4, 8, 9, 6, 3, 2}
print(my_set)

{2, 3, 4, 6, 8, 9}


In [ ]:
a = set()

In [ ]:
a.add(10)
a

{10}

In [ ]:
a.add(20)
a

{10, 20}

In [ ]:
a.add(20)
a

{10, 20}

In [ ]:
my_set = {34, 67, 89}
my_set.update([10, 67, 89])
print(my_set)

{10, 89, 34, 67}


In [ ]:
my_set

{10, 34, 67, 89}

In [ ]:
my_set.remove(34)

In [ ]:
my_set

{10, 67, 89}

In [ ]:
#union---
A = {1, 2,3, 4, 5}
B= {4, 5, 6, 7, 8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
A.intersection(B)

{4, 5}

In [ ]:
A.difference(B)

{1, 2, 3}

In [ ]:
A-B

{1, 2, 3}

In [ ]:
B-A

{6, 7, 8}

In [ ]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [ ]:
my_dict = {"HP":"SHM", "UP":"LK", "TN":"CHN"}
type(my_dict)


dict

In [ ]:
print(my_dict)

{'HP': 'SHM', 'UP': 'LK', 'TN': 'CHN'}


In [ ]:
len(my_dict)

3

In [ ]:
my_dict["HP"]

'SHM'

In [ ]:
#keys() -- this method return the keys of dictionary
list(my_dict.keys())

['HP', 'UP', 'TN']

In [ ]:
#values()-- this method return values of your dictionary
list(my_dict.values())

['SHM', 'LK', 'CHN']

In [ ]:
#items() -- this method return items of your dictionary
list(my_dict.items())

[('HP', 'SHM'), ('UP', 'LK'), ('TN', 'CHN')]

In [ ]:
my_dict = {"Name":"Aman", "Marks_list":[45, 89, 67, 68]}
type(my_dict)

dict

In [ ]:
my_dict.update({"college":"Shoolini"})
print(my_dict)

{'Name': 'Aman', 'Marks_list': [45, 89, 67, 68], 'college': 'Shoolini'}


In [ ]:
my_dict.update({"Name":"Jai"})
print(my_dict)

{'Name': 'Jai', 'Marks_list': [45, 89, 67, 68], 'college': 'Shoolini'}


In [ ]:
age = int(input("Enter your age: "))
if age <= 21:
  print("You are too young for marriage")
elif age >= 60:
  print("You are too old for marriage")
else:
  print("we will find perfact match for you")

Enter your age: 21
You are too young for marriage


In [ ]:
#for loop - this loop apply on sequence(string, list, tuple and range())
my_sub = "Solan"
for i in my_sub:
  print(i)

S
o
l
a
n


In [ ]:
for i in range(0, 5, 1):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(0, 5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
#indexing
my_sub = "Machine learning"
for i in range(len(my_sub)):
  print(my_sub[i], i)

M 0
a 1
c 2
h 3
i 4
n 5
e 6
  7
l 8
e 9
a 10
r 11
n 12
i 13
n 14
g 15


In [ ]:
my_sub = "Machine learning"
for i in range(-1, -(len(my_sub)+1), -1):
  print(my_sub[i], i)

g -1
n -2
i -3
n -4
r -5
a -6
e -7
l -8
  -9
e -10
n -11
i -12
h -13
c -14
a -15
M -16


In [ ]:
#while loop--this loop execute upto condition is true

In [ ]:
i = 0 #initialization
while i<5:#condition
  print(i)
  i+=1 #increment  i = i+1
print(i)

0
1
2
3
4
5


In [ ]:
#loops control statement
i = 0
while i<5:
  if i == 3:
    break  # break your loop
    print(i)
  else:
    print(i)
  i+=1

0
1
2


In [ ]:
i = 0
while i<5:
  i+=1
  if i == 3:
    continue  # skip the current iteration
    print(i)
  else:
    print(i)


1
2
4
5


In [ ]:
i = 0
while i<5:
  i+=1
  if i == 3:
    pass  # skip the current iteration
    print(i)
  else:
    print(i)

1
2
3
4
5


In [ ]:
#user defined function
def add():
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  c = a+b
  return c


In [ ]:
print(add())

Enter first number: 10
Enter second number: 20
30


In [ ]:
def add():
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  c = a+b
  print(c)
  return c


In [ ]:
print(add())

Enter first number: 6
Enter second number: 7
13
13


In [ ]:
#positional argument
def add(a, b):
  c = a+b
  return c

In [ ]:
print(add(10, 20))

30


In [ ]:
#default argument
def add(a = 20, b = 30):
  c = a+b
  return c

In [ ]:
print(add())

50


In [ ]:
print(add(50))

80


In [ ]:
#keyword arguments
def interest(p, r, t):
  i = (p*r*t)/100
  return i

In [ ]:
print(interest(t = 2, p = 100, r = 10))

20.0


In [ ]:
#mixed arguments(positional, keyword)

In [ ]:
interest(100, r= 10, t = 2)

20.0

In [ ]:
#variable length argument
#non-keyword variable length aruments
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

In [ ]:
test(7, 5, 4, 3, 2)

(7, 5, 4, 3, 2)
5
<class 'tuple'>


In [ ]:
def addition(*args):
  sum = 0
  for i in args:
    sum+=i
  return sum

In [ ]:
addition(3, 4, 5, 9)

21

In [ ]:
#keyword variable length arguments
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

In [ ]:
test(a = 10, b = 20, c = 30)

{'a': 10, 'b': 20, 'c': 30}
<class 'dict'>
3


In [ ]:
def pass_student(**kwargs):
  pass_student_list = []
  for key, value in kwargs.items():
    if value >=40:
      pass_student_list.append(key)
  return pass_student_list

In [ ]:
pass_student(A = 60, B= 30, C = 80, D = 39)

['A', 'C']

In [ ]:
import numpy as np

In [ ]:
oned_array = np.array([3, 4, 5, 6])
print(oned_array)

[3 4 5 6]


In [ ]:
twod_array = np.array([[3, 5, 6],
                       [9, 8, 1]])
print(twod_array)

[[3 5 6]
 [9 8 1]]


In [ ]:
#array inspection
#shape--- find the shape of array
oned_array = np.array([3, 4, 5, 6])
print(oned_array)
oned_array.shape

[3 4 5 6]


(4,)

In [ ]:
twod_array = np.array([[3, 5, 6],
                       [9, 8, 1]])
print(twod_array)
twod_array.shape

[[3 5 6]
 [9 8 1]]


(2, 3)

In [ ]:
threed_array = np.array([[[9, 8, 7],[7, 5, 4]],
                        [[9, 3, 2],[9, 4, 3]]])
print(threed_array)
threed_array.shape

[[[9 8 7]
  [7 5 4]]

 [[9 3 2]
  [9 4 3]]]


(2, 2, 3)

In [ ]:
#ndim-- find the dimension of array
twod_array = np.array([[3, 5, 6],
                       [9, 8, 1]])
print(twod_array)
twod_array.ndim

[[3 5 6]
 [9 8 1]]


2

In [ ]:
#dtype-- find the data type
twod_array.dtype

dtype('int64')

In [ ]:
#size -- total number of item in array
twod_array = np.array([[3, 5, 6],
                       [9, 8, 1]])
print(twod_array)
twod_array.size

[[3 5 6]
 [9 8 1]]


6

In [ ]:
import numpy as np
twod_array = np.array([[3, 5, 6],
                       [9, 8, 1]])
print(twod_array)
twod_array.astype(float)

[[3 5 6]
 [9 8 1]]


array([[3., 5., 6.],
       [9., 8., 1.]])

In [ ]:
#zeros array
zero_array = np.zeros((3, 4), dtype = int)
print(zero_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
ones_array = np.ones((3, 4), dtype = int )
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
print(ones_array*99)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [ ]:
my_array = np.full((3, 3), 100)
print(my_array)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
random_array = np.random.random((3, 4))
print(random_array)

[[0.41536475 0.96289915 0.3639109  0.99098807]
 [0.555464   0.99069066 0.89356646 0.12343815]
 [0.34538989 0.03462779 0.77651513 0.67722767]]


In [ ]:
random_intarray = np.random.randint(2, 10, (3, 4))
print(random_intarray)

[[6 9 8 4]
 [4 6 5 7]
 [7 9 2 6]]


In [ ]:
arange_array = np.arange(2, 20, 2, dtype = float)
print(arange_array)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
a = np.random.randint(1, 6, (2, 2))
print(a)
b = np.random.randint(1, 6, (2, 2))
print(b)
print(a+b)

[[3 1]
 [5 1]]
[[3 2]
 [5 4]]
[[ 6  3]
 [10  5]]


In [ ]:
#(3, 4) and(1, 1)
a = np.random.randint(1, 6,(3, 4))
print(a)
b = np.random.randint(1, 6, (1, 1))
print(b)
print(a+b)

[[3 4 4 4]
 [4 5 4 2]
 [1 4 4 5]]
[[1]]
[[4 5 5 5]
 [5 6 5 3]
 [2 5 5 6]]


In [ ]:
#(1,4) and(4,1)
#(1, 5) and(5, 1)
a = np.random.randint(1, 6, (1, 4))
print(a)
b = np.random.randint(1, 6, (4, 1))
print(b)
print(a+b)

[[1 2 1 2]]
[[1]
 [5]
 [1]
 [4]]
[[2 3 2 3]
 [6 7 6 7]
 [2 3 2 3]
 [5 6 5 6]]


In [ ]:
a = np.random.randint(1, 6, (2, 4))
print(a)
b = np.random.randint(1, 6, (4, 2))
print(b)
print(a+b)

[[3 4 2 3]
 [1 5 1 1]]
[[5 4]
 [1 2]
 [5 1]
 [3 5]]


ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [ ]:
#(1,4)
#(3, 4)
a = np.random.randint(1, 6, (1, 4))
print(a)
b = np.random.randint(1, 6, (3, 4))
print(b)
print(a+b)

[[4 3 1 2]]
[[4 4 5 5]
 [3 3 2 2]
 [5 2 2 4]]
[[8 7 6 7]
 [7 6 3 4]
 [9 5 3 6]]
